language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: HMqRgF358AzBno/MhDr/FrRVQivOElv5Pg+LXuUQgoKTsn8dLLFQTjrR6cnTpmEUcQFpgY4ZOtlqNAn2RoLQywDV2bCOGhwk6HXN3R5+7inLOgXRjMfIFFtM/2C4Wxg71pC301IQLMI++FBYrhe85VwUAOfwfUvuEn7A2Hxo72ahSoK2hVB2bVYP/20ZelHTxrLQ3ll+4awKUw/2sbMCSLPeWEbdATqr4ZqMRDQ+gUnT+LAoPZIm26FhakjvO2A+VQt4lH39LsG0jLc3YrFhpzLv8gX5ZzYxVAFKQfI7w+CrAC+vwstIk3oH8ZU9M8Zc3LfYFqvJ7NlNlLx7AD+YNVlZYZ0mU+eNW9UDk6mMDYGPa1cLG93yp3AT8kphxLTNxSskWdk4tA5bgRx4BzF+1Tz08w0bUkAKNl2mmBp1uHE1A7RIPgDu+foc3NOnxDV9EANOjwgo2GyggUPNInw2UMmVpWvfXwFoSgOLsIpPpuOyehw/iU4w+3xpsE3hhrb6+djP94xKVlonc14KxAfyKxfA93p0NiugiwLoMu0uK2uPZFXb0ckiCgrtXGMmV1Vh3owFt8AC79KICl8BxaSYy9UVMD+FMxcLeyvzpb7aboakzAXVRLCSCEg4DAGez0CUTmAcnM7mjNqODUcq3xHhvTXkZgZdpe9aXVB05EyeOrg=
  app: shrouded-plains-20805
  on:
    repo: lakerfan1994/react-trello-testing
